### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by demhademha** [gioblu/BIPLAN#5]
Good evening, could you please provide build instructions as well as required dependencies?
regards

**Comment by gioblu** [comment]
Ciao @demhademha here there are instructions to build the compiler: https://github.com/gioblu/BIPLAN/tree/master/examples/LINUX/bcc-compiler and here the instructions to build the interpreter: https://github.com/gioblu/BIPLAN/tree/master/examples/LINUX/biplan-interpreter 

BIPLAN do not need any external dependency to operate apart of some headers of the std library which are generally available in a linux environment. Let me know how it goes and if you need any support, happy tinkering.

**Comment by demhademha** [comment]
Hi, thanks for your support and for clarifying. 
I will now close this issue.
